added waiter for the the ephemeral cluster to come

diff --git a/packages/cluster_types/nc3prime/manifests/type/ephemeral_bootstrap/kustomization.yaml b/packages/cluster_types/nc3prime/manifests/type/ephemeral_bootstrap/kustomization.yaml
--- a/packages/cluster_types/nc3prime/manifests/type/ephemeral_bootstrap/kustomization.yaml
+++ b/packages/cluster_types/nc3prime/manifests/type/ephemeral_bootstrap/kustomization.yaml
@@ -1,3 +1,35 @@
+secretGenerator:
+  - name: check-ehpemeral-readiness-secret
+    options:
+      disableNameSuffixHash: true
+    literals:
+    - |
+        script.sh=#!/bin/sh
+        echo "Wait for apiserver to become available" >&2
+        N=0
+        MAX_RETRY=30
+        DELAY=60
+        KUBECONFIG=/cache/ephemeral_build_iso/adminConfig.yaml
+        KUBECONFIG_EPHEMERAL_CONTEXT=kubernetes-admin@kubernetes
+        until [ "$N" -ge ${MAX_RETRY} ]
+        do
+          if timeout 20 kubectl --kubeconfig $KUBECONFIG --context $KUBECONFIG_EPHEMERAL_CONTEXT get node >&2; then
+            break
+          fi
+
+          N=$((N+1))
+          echo "$N: Retrying to reach the apiserver" >&2
+          sleep ${DELAY}
+        done
+
+        if [ "$N" -ge ${MAX_RETRY} ]; then
+          echo "Could not reach the apiserver" >&2
+          exit 1
+        fi
+
+        echo "List all pods" >&2
+        kubectl --kubeconfig $KUBECONFIG --context $KUBECONFIG_EPHEMERAL_CONTEXT get pods --all-namespaces >&2
+
 generators:
 - ../functions/hostgenerator-ephemeral
 - ../functions/fileserver
